### PR TITLE
WIP on feature JSON/API view

### LINKED ISSUE #60: add an HTTP API
It might be time to add an HTTP API for tools/websites that want to integrate with explainshell (issue #4 is one).

My current thought is to add a GET endpoint at `/api/explain` with a `cmd` parameter, similar to /explain. The response could be a JSON that looks something like this:

```
{
  'help' : ['help text 0', 'help text 1', ..],
  'cmd' : <parsed command>
  'matches' : [{'startindex' : x,
                    'endindex' : y,
                    'helpindex' : <index into help array, or -1 if unknown>], [..]]
}
```

The rationale for not inlining the help text into matches is that there can be duplicates. The reason for including `cmd` in the response is that it's possible for explainshell to change it, e.g. due to unicode which is not supported yet.

Example:

```
GET /api/explain?cmd=echo -n

{
  'help' : ['display a line of text',
             '-n     do not output the trailing newline'],
  'cmd' : 'echo -n'
  'matches' : [{'startindex' : 0, 'endindex' : 4, 'helpindex' : 0},
                   {'startindex' : 5, 'endindex' : 7, 'helpindex' : 1}]
}
```

### PR DESCRIPTION
**Pull request by asfaltboy**
work in progress in attempt to resolve #60 

This currently returns a json with the same context as the explain rendered view; in fact, it is simply a response format wrapper around the same view. Some of the returned does not make a lot of sense to me, it seems tightly coupled with the HTML formatting.

I believe we should further separate/generalize the actual data from "_HTML template formatting specific_" context variables.

### CODE REVIEW

**Comment by idank** [comment]
Thanks for showing interest.

It looks like this simply translates whatever I happened to pass into to the template to json.. which isn't a very good API as you mentioned.

I think we need to return something closer to what I have in the bug report, which should be more friendly consume.

**Comment by asfaltboy** [comment]
I completely agree; in fact I feel there are 2 approaches to returning "clean" data:

1. In our generic wrapper, if the format is `json`, cleanup and rewrite the returned data structure.
2. Refactor the parts of `explaincommand` that relate to the HTML template rendering, out to our generic wrapper, in case the format is `html`.

Of these, I feel that the second is a more logical refactoring

In both cases the data returned by the API shall be similar to the structure initially described in issue #60.

**Comment by idank** [comment]
Looking at explaincommand, it's very heavily coupled with the html representation, I think it might be easier to simply write another function that does what we need for the API, rather than find a way to generalize the existing one.

If you'd like to take a shot at it and get something working, I'd be glad to review it and suggest fixes.

**Comment by asfaltboy** [comment]
Right, and we switch in the explain view? So e.g "explaincommand" would become "explaincommand_html" and we'd add another "explaincommand_api" to return the dictionary for result?

**Comment by idank** [comment]
Sure.

**Comment by jimmyppi** [comment]
Is anyone working on this? I could take a shot at it if not.

**Comment by asfaltboy** [comment]
I'm not able to devote time for this unfortunately, @jimmyppi can have this 👍

**Comment by akshay2000** [comment]
@jimmyppi Have you taken this any further?

**Comment by jimmyppi** [comment]
Nope

**Comment by akshay2000** [comment]
In that case, @idank, can you point me to the correct abstraction level to expose a REST API? Where can I get all the required details for such an API?

**Comment by chrismwendt** [comment]
:wave: I picked this up. Once https://github.com/asfaltboy/explainshell/pull/2 is merged in (to `asfaltboy/explainshell`), this PR should automatically update and be ready to merge 👌

**Comment by idank** [comment]
Cool, waiting for the pull request!

**Comment by chrismwendt** [comment]
@idank If you don't want to wait for @asfaltboy to merge https://github.com/asfaltboy/explainshell/pull/2, you can just merge in my branch https://github.com/chrismwendt/explainshell/tree/feature/api-view

**Comment by chrismwendt** [comment]
@idank I simplified the JSON structure so that it's not so tied to the format that the HTML templates expect.

**Comment by asfaltboy** [comment]
Awesome work @chrismwendt! I also rebased my branch over latest `idank:master` branch.

@idank please let us know what you feel of this updated PR.

**Comment by idank** [comment]
Alright, thanks for working on this! Give me a few days, I'm a little swamped lately.

**Comment by pryorda** [comment]
👍 Watching this.

**Comment by kennethreitz** [comment]
watching this!

**Comment by pryorda** [comment]
@chrismwendt Should the flag parsing work in VS Code? I'm running your server via make serve on your feature branch.

**Comment by chrismwendt** [comment]
@pryorda Yes, it should work in VS Code as shown in https://github.com/mads-hartmann/bash-language-server/pull/45. Make sure you're running the latest bash-language-server and this branch of explainshell, then add the setting `bashIde.explainshellEndpoint` to your settings (I just noticed that the prefix was wrong, it used to be `bash`, now it's `bashIde`).

**Comment by pryorda** [comment]
Interesting... I can't get it work correctly

bash-language-server 
{code}
CO007-mac ➜  pprometheus git:(DEVOPS-1381-more) bash-language-server -v
Version is 1.3.1
CO007-mac ➜  pprometheus git:(DEVOPS-1381-more)
{code}
Running the lastest extension, and your branch via make serve.

**Comment by chrismwendt** [comment]
@pryorda Are you also running MongoDB with flag data loaded? It's painful to set that all up, so I created https://hub.docker.com/r/chrismwendt/codeintel-bash-with-explainshell/

Try running it like this:

```
docker run --name bash-explainshell --rm -p 5000:5000 chrismwendt/codeintel-bash-with-explainshell
```

**Comment by pryorda** [comment]
@chrismwendt Let me try that again. I think I did it with the old version of the VSCode ext.

**Comment by pryorda** [comment]
I tried it again and I still dont see the flags. Do I need to hold some hot key to get the flag docs?

**Comment by chrismwendt** [comment]
No, check the Output panel in VS Code (and select the bash language server) and see if there are any errors there.

**Comment by pryorda** [comment]
image

No errors and still doesnt add anything to logs of the docker container either.

**Comment by chrismwendt** [comment]
Strange - I'd try opening bash-language-server in VS Code, putting a breakpoint on https://github.com/mads-hartmann/bash-language-server/blob/00941c001ca342c8a9c1b647b2a1b7ea703e5fc6/server/src/server.ts#L104, hitting F5, opening `build.sh`, and single-stepping from there to see if it sends a request to explainshell or not. I'm guessing the setting isn't set, the endpoint isn't up, or there's simply no data being returned.

**Comment by pryorda** [comment]
I did npm install -g bash-language-server which doesn't install the correct version. Ran npm install -g from within the server dir and everything started working correctly.

Thanks

**Comment by maximbaz** [comment]
A friendly ping @chrismwendt & @asfaltboy, have you had a chance to look at the code review comments?

**Comment by chrismwendt** [comment]
Yes, but I won't be able to work on this in the near future.

**Comment by saulocastelo** [comment]
Updates?
@chrismwendt @asfaltboy

**Comment by lanox** [comment]
any updates on this ?

**Comment by cmackenzie1** [comment]
bump

> any updates on this ?

**Comment by Sanjit1** [comment]
bump

**Comment by Sanjit1** [comment]
+ gitignore is conflicting

**Comment by thuandt** [comment]
cc @asfaltboy

**Comment by samedguener** [comment]
Seems like the Docker image has been removed. Any updates on this one?

**Comment by asfaltboy** [comment]
I finally realised I'm never going to complete this work. If another contributor wants to take over, please go ahead and use this branch for inspiration.

**Pull request closed without merging**
