### PR TITLE
Docker upgrade and man page seeding

### PR DESCRIPTION
**Pull request by timothybrush**
Thank you for developing this tool.  I was introduced to it just yesterday and saw some areas that could be made easier to run as standalone.  I see that you are working on a Python 3 branch but I didn't know how far you are from release, so I didn't focus on that.

I merged a few changes others had made in forks that seemed useful.  Then, I focused on slimming down your Docker image and automating some of your previous steps.  I also seeded the manpages directory with man pages from a few Linux distributions and created an import script to load them.  The pages add a bit of weight to the repository but nothing too significant.

Hopefully my updates will make it easier on you to update and continue work on the parser.  Adding the Linux distributions to the manpages directory should also open up the possibility for others to issue pull requests with missing manpages.  I realize there is likely some duplication but I didn't have time to compare each distribution's man pages against others.

List of changes:
    - Build on top of python:2.7.18-slim (reduced size by 60%)
    - man and groff now function correctly inside Docker container
    - Updated Python packages while remaining on Python 2
    - Added unprivileged user to run Python webserver (improved security)
    - Automatically import classifiers on docker-compose up
    - Moved test man pages under `manpages/_test` and updated test-manager.py
    - Added man page import script with instructions
    - Seeded manpages: CentOS 7 & 8, openSUSE 15, Ubuntu 18.04 & 20.04
    - Updated README.md and moved Running on Docker above Running locally

### CODE REVIEW

**Comment by timothybrush** [comment]
# Fixes issues:

Upgraded man pages #65
- Links now point to Ubuntu Focal instead of Ubuntu Precise

Problem starting docker-compose #184
- docker-compose.yml and Dockerfile updated and working.

Parse newer manpages #219
- Newer man pages for Ubuntu Bionic (18.04) and Focal (20.04) under manpages

No man page for journactl #233 (Note: command is `journalctl`)
- Available under CentOS 7 & 8, openSUSE 15, Ubuntu 18.04 & 20.04 man pages.  Appears to parse mostly. 

Having trouble importing man pages #260
- Imported man pages without issue. Import script will import multiple man pages if located under manpages directory.

nltk-2.0.5 is obsolete #261
- Bumped versions on all Python modules.  Upgraded to those that still work with Python 2.7.x.

docker-compose build fails #267
- docker-compose.yml and Dockerfile updated and working


## Should help with the following issues:

[feature request] add FreeBSD/Mac OS X man pages #5
- Added macos11 pages under manpages.  Don't have a FreeBSD or OpenBSD system running at the moment. Haven't tried parsing them.

nohup man page missing #119
- Included under multiple distributions, parsing iffy

POSIX/ Use several sources for manpages #147
- Very rough way of handling different Linux/BSD/macOS distributions but hopefully it'll help your testing.  Would need better linking logic for online pages, everything currently goes to Ubuntu Focal.

Can't explain Docker container commands #203
- Updated man page under multiple distributions, unfortunately doesn't parse correctly.

Is CentOS/RHEL Supported? #268
- Added man pages for CentOS 7 & 8, which mostly work. CentOS/RHEL also use man subsections (i.e. `man1p`) that don't currently work.

**Comment by Footur** [comment]
@idank It would be nice if you could take a look here. :slightly_smiling_face:

**Comment by idank** [comment]
Sorry for the long delay, wow!

There are a lot of really good changes here. Can we start with the more straight forward changes first? E.g. the ones that don't update the man pages. We can follow up with that as it's more complicated to deal with.

**Comment by tobiashochguertel** [comment]
This works also with podman-compose. I tested it with my MacBook Pro (Intel).
I had to do a small fix before it was able to run: `chmod o+rwx ./` in the root of the git-working-copy (`gh pr checkout 277`). Then everything went fine, and the web container was able to write to the volume-mount from the [docker-compose.yml file](https://github.com/timothybrush/explainshell/blob/8299aebf092806c1f8da8fb37d7c26c890d4910f/docker-compose.yml#L12). 

I would just merge it?

**Pull request closed without merging**
