### PR TITLE
Implement text parts of logo using css

### PR DESCRIPTION
**Pull request by avindra**
This is initial work towards #155 

The logo currently has white pixels in the background, which makes implementing a dark theme difficult.

This work would also allow us to change the black parts of the logo to something more readable once the "dark" theme is active.

### CODE REVIEW

**Comment by stoivo** [comment]
I am so excited to see something else use the docker image I setup. So I tested out you PR.
Amazing, I cant see the difference on screen, but I know it is better. Flexible and faster (less data transfer).

**Before:**
before

**After:**
after

I am mostly a backend developer and structure data. Still very curious how you found wich font which has been in use to create the the png. Are you allowed to the your magic trick?

**Comment by avindra** [comment]
There are many reverse font lookup sites, but I determined the font name because the "About" link actually uses the same font already :)

Thanks again for the docker work, its tremendous :smile:

**Comment by idank** [comment]
Good stuff! Thanks for this. I'm a bit swamped at work but I will get to this in a few days.

**Comment by idank** [comment]
It even looks crisper on my browser. Sweet.

The only unfortunate thing is that it looks awful if the font loading fails. I guess we can live with that. (Or just create a transparent image.)

Merged, thanks!

**Comment by avindra** [comment]
Thanks! The only complaint I have now is that the shell looks really blurry compared to the text.

Do you have a higher resolution source for it?

**Comment by idank** [comment]
Yeah that's unfortunate. Pretty sure I just googled 'shell' (or shell image, shell svg) and took it off the images tab. If you can find a high quality one that looks similar, that'd be fine too.

**Pull request closed without merging**
