### PR TITLE
Added dark theme

### LINKED ISSUE #155: Dark theme
I love this site - and would love to see something like a dark theme to make it easier on the eyes.

Then allow users to configure what theme they want to use (cached in localStorage or otherwise to make things simple).

I am a web developer so I could take a stab at it, but would like to hear your thoughts first.

### PR DESCRIPTION
**Pull request by anestv**
The user selects a theme using a dropdown menu
Their preference is saved in localStorage

More themes can be added later if needed

Closes #155

### CODE REVIEW

**Comment by idank** [comment]
This seems awesome, thanks. Can you post a screenshot?

**Comment by anestv** [comment]
Homepage:
homepage
homepage with default theme
About:
about page
Explain page:
an explain page

**Comment by anestv** [comment]
whoa wait a sec, just realised that the logo is missing

**Comment by idank** [comment]
It mostly looks fine to me but I dislike the drop down. Can you move it so it's to the left of 'about' below the logo, and call it 'theme'? And instead of the drop down, perhaps use this style that fits with the rest of the UI?

screen shot 2017-10-12 at 10 39 59 pm

**Comment by anestv** [comment]
I'll try that

**Comment by anestv** [comment]
How is that?
default
default

**Comment by idank** [comment]
Better but I forgot about the search box. Maybe move it to the right side of the logo?

Also I think the theme names in the drop down would look better in the monospace font. The menu font looks weird.

**Comment by stoivo** [comment]
I think is better to move the theme select to the right side since most users read from left to right and will use the search more often than the theme select. 

@anestv, very nice to see someone taking this issue :D

**Comment by anestv** [comment]
What about this? 
default

**Comment by idank** [comment]
I think it looks great.

**Comment by idank** [comment]
Have you been running this for a while now? Is it ready?

**Comment by anestv** [comment]
I think it is ready, but I wasn't able to setup the server successfully so I'm not sure

**Comment by anestv** [comment]
Ok, I set it up and tested it and it's ready

**Comment by idank** [comment]
ack, will merge as soon as I can. Thanks for being patient!

**Comment by anestv** [comment]
Any update?

**Comment by idank** [comment]
Sorry, slipped my mind. I'll take care of it on the weekend, promise. :)

**Comment by Ninja101** [comment]
@idank ¯\_(ツ)_/¯

**Comment by idank** [comment]
Ah darn it! Ok, I'm not going to commit on a day, but I'll definitely get it to it SOON. :) Sorry!

**Comment by idank** [comment]
Merged, yay! Thanks for being patient, it looks pretty nice!

**Pull request closed without merging**
