### PR TITLE
Redos option fix

### PR DESCRIPTION
**Pull request by theWorstComrade**
https://huntr.dev/bounties/c85354c7-4490-4fad-a32c-03f9f4bdcb63/

### CODE REVIEW

**Comment by stoivo** [comment]
What does it fix?
The report is not public?

**Comment by idank** [comment]
An inefficiency in a regular expression can cause high parse times. @theWorstComrade can you open up the report? I think it's fine.

**Comment by theWorstComrade** [comment]
@idank @stoivo As far as I know, the huntr platform does not give me possibility to disclose the report. This happens automatically when the bug is marked as fixed. 

Printed version:
[Inefficient Regular Expression Complexity vulnerability found in explainshell.pdf](https://github.com/idank/explainshell/files/7787889/Inefficient.Regular.Expression.Complexity.vulnerability.found.in.explainshell.pdf)

**Comment by idank** [comment]
merged after squashing, thanks

**Pull request closed without merging**
