### PR TITLE
Dockerfile improved

### PR DESCRIPTION
**Pull request by k3ck3c**
Modified Dockerfile

### CODE REVIEW

**Comment by stoivo** [comment]
This will reduce the amount of images created. Is the any other benefits of this?

PS: I set up this DockerFile, but not much experience with Docker

**Comment by k3ck3c** [comment]
Hello

The docker image will have less layers and will be spammer.

I am unable to use your docker compose at the moment, do you have a
detailed doc?

Regards


Le vendredi 7 avril 2017, Simon <notifications@github.com> a écrit :
> This will reduce the amount of images created. Is the any other benefits
of this?
>
> PS: I set up this DockerFile, but not much experience with Docker
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/a0B7SbwlLj95bnxwQBlSIRsxNpq48XIpl02UvKXIBuhiiSbQJsLllEX3UahvfT_upyyIDROdf2IVJC_bVPsDv5ysErBXoDevw39vkgn6hZl5nS5yaKr4VZA7ap24iVhL3knGadvJMvhkOXgPkiTTYMzUDEU1Gw=s0-d-e1-ft#https://github.com/notifications/beacon/AC-z07vuYALXiNIt7e8LNO0mEYXZwwbqks5rthBEgaJpZM4M1Zfh.gif>

**Comment by k3ck3c** [comment]
Hello sorry for the typos on my phone

>>>The docker image will have less layers and will be smaller


2017-04-07 12:48 GMT+02:00 k3c palmi <k3ck3c@gmail.com>:

> Hello
>
> The docker image will have less layers and will be spammer.
>
> I am unable to use your docker compose at the moment, do you have a
> detailed doc?
>
> Regards
>
>

**Comment by stoivo** [comment]
You PR looks good. This way it consume less disk.

I wrote some lines who I set up with docker-compose https://github.com/idank/explainshell#start-up-a-local-web-server-with-docker

**Comment by k3ck3c** [comment]
The following Dockerfile based on Alpine should be smaller

more Dockerfile_alpine
FROM alpine

MAINTAINER Simon Toivo Telhaug <simon.toivo@gmail.com>

RUN apk add  --update man man-pages py-pip

ADD ./requirements.txt /tmp/requirements.txt
ENV PYTHONHTTPSVERIFY 0
RUN pip install --upgrade pip \
&& python --version \
&& pip install -r /tmp/requirements.txt

ADD ./ /opt/webapp/
WORKDIR /opt/webapp
EXPOSE 5000
 
CMD ["make", "serve"]

But I need to test it before

$ docker images | grep explainshell
k3ck3c/explainshell_alpine                      latest              6e14f0c74469        29 hours ago        92.66 MB
k3ck3c/explainshell                             latest              2d7d7295c47c        31 hours ago        724.8 MB

**Comment by stoivo** [comment]
Thats cool but I prefer to run a more similar docker image as my server.

**Comment by stoivo** [comment]
@idank, can you merge this?

**Comment by idank** [comment]
Done, thanks.

**Pull request closed without merging**
