### PR TITLE
README.md: Fix header formatting

### PR DESCRIPTION
**Pull request by mgalgs**
The first line was presumably supposed to be a markdown header,
but was missing a space after the `#`.  Also, it renders a bit large to
as a level-1 header, so make it a level-2 header.

### CODE REVIEW

**Comment by mgalgs** [comment]
@idank Done

**Comment by willyb321** [comment]
Lol someone opened another PR (#178) to do the exact same thing.

**Comment by mgalgs** [comment]
> Lol someone opened another PR (#178) to do the exact same thing.

haha lots of OCD HN readers, I assume ;)

**Comment by idank** [comment]
Thanks for sending this! By the way, I'm pretty sure github's markdown renderer became more strict with the spacing there. It used to look fine, even though the syntax might require the space.

**Comment by mgalgs** [comment]
Oh interesting... That explains why I've been noticing a few of these lately.

**Pull request merged**
